#   For configuration options documentation, see:
#   https://docs.haskellstack.org/en/stable/configure/yaml/

packages: [ . ]

#   We mostly try to use the package versions specified by this snapshot,
#   but in some cases have to roll back to previous versions to satisfy the
#   requirements of 'g2' and some of its dependencies. This also serves
#   as a list of things to look at to update g2 to use recent versions.
snapshot: lts-23.27         # Gives GHC 9.8.4 by default.

extra-deps:
    #   'language-sygus' is not in Hackage, so we must add it here.
    - language-sygus-0.1.1.3
    - text-2.0                      # for language-sygus

    #   Stack prunes parsec from ghc-boot; it must be explicitly specified.
    - parsec-3.1.18.0               # latest as of this writing

    #   Revision rollbacks required by g2 library.
    - Cabal-3.10.3.0
    - Cabal-syntax-3.10.3.0
    - bimap-0.3.3
    - optparse-applicative-0.17.1.0
    - ansi-wl-pprint-0.6.9          # for optparse-applicative
    - ansi-terminal-1.0.2           # for ansi-wl-pprint
    - ansi-terminal-types-0.11.5    # for ansi-terminal
    - regex-base-0.94.0.2
    - split-0.2.3.5
    - tasty-quickcheck-0.10.1.2
   #- text-2.1                      # language-sygus requires older version
