{-# LANGUAGE OverloadedStrings, CPP, FlexibleContexts, BangPatterns #-}

module G2.Translation.ValidateState ( validateStates
                                   , validateStatesGHC
                                   , loadStandard
                                   , loadToCheck
                                   , createDeclsStr
                                   , createDecls
                                   , runHPC
                                   , adjustDynFlags
                                   , loadSession
                                   , validateState
                                   , printStateOutput
                                   , toEnclodeFloat
                                    ) where
#if MIN_VERSION_GLASGOW_HASKELL(9,0,2,0)
import GHC.Driver.Session
import qualified GHC.Data.EnumSet as ES
#else
import DynFlags
import qualified EnumSet as ES
#endif

import GHC hiding (Name, entry, Id)
import GHC.LanguageExtensions

import GHC.Paths
import Control.Monad

import G2.Translation.GHC (SourceError)

import qualified Data.Foldable as F
import Data.Either
import qualified Data.HashSet as HS
import Data.List
import Data.Maybe
import qualified Data.Text as T
import qualified Data.Text.IO as T
import qualified Data.Sequence as S
import Text.Regex
import Unsafe.Coerce
import qualified Data.HashMap.Lazy as H
import G2.Config
import G2.Initialization.MkCurrExpr
import G2.Interface.ExecRes as I
import G2.Language
import G2.Translation.Haskell
import G2.Translation.Interface
import G2.Translation.TransTypes
import G2.Lib.Printers
import Control.Exception

import System.Directory
import System.FilePath
import System.IO.Error
import System.Process
import System.Timeout

import Control.Monad.IO.Class

-- | Load the passed module(s) into GHC, and check that the `ExecRes` results are correct.
validateStates :: [FilePath] -> [FilePath] -> HS.HashSet (Maybe T.Text) -> String -> [String] -> [String] -> [GeneralFlag] -> String -> Bindings
               -> [ExecRes t]
               -> IO ( [ValidateRes]
                     , Bool -- ^ Are all "Any" requirements satisfied?
                     )
validateStates proj src modN entry chAll chAny gflags comp_func b in_out = do
    runGhc (Just libdir) (do
        adjustDynFlags
        loadToCheck (map dirPath src ++ proj) src modN gflags
        rs_anys <- mapM (\er -> do
                let s = final_state er
                let pg = updatePGValNames (concatMap (map Data . dataCon) $ type_env s)
                       . updatePGTypeNames (type_env s)
                       . flip (foldr updateQualMods) (catMaybes $ HS.toList modN)
                       . setStrictCase True
                       $ mkPrettyGuide ()
                _ <- createDecls pg s (H.filter (\x -> adt_source x == ADTG2Generated) (type_env s))
                validateStatesGHC pg comp_func modN entry chAll chAny b er) in_out
        let chck_anys = all or . transpose $ map snd rs_anys
        return (map fst rs_anys, chck_anys))

-- | Convert g2 generated types into readable string that aim to notify the environment about the types generated by g2
-- The type is formatted as the following:
-- data name bound_ids = datacons 
creatDeclStr :: PrettyGuide -> State t -> (Name, AlgDataTy) -> String
creatDeclStr pg s (x, DataTyCon{data_cons = dcs, bound_ids = is}) =
    let
        x' = T.unpack $ printName pg x
        ids' = T.unpack . T.intercalate " " $ map (printHaskellPG pg s . Var) is
        wrapParens str = "(" <> str <> ")" 
        dc_decls = map (\dc -> printHaskellPG pg s (Data dc) <> " " <> T.intercalate " " (map (wrapParens . mkTypeHaskellPG pg) (argumentTypes (typeOf (tyvar_env s) dc)))) dcs
        all_dc_decls = T.unpack $ T.intercalate " | " dc_decls
        derive_eq = if not (any isTyFun $ concatMap (argumentTypes . typeOf (tyvar_env s)) dcs) then " deriving Eq" else ""
    in
    "data " ++ x' ++ " " ++ ids'++ " = " ++ all_dc_decls ++ derive_eq
creatDeclStr _ _ _ = error "creatDeclStr: unsupported AlgDataTy"

-- | Compile with GHC, and check that the output we got is correct for the input
validateStatesGHC :: GhcMonad m => PrettyGuide -> String -> HS.HashSet (Maybe T.Text) -> String -> [String] -> [String] -> Bindings -> ExecRes t -> m (ValidateRes, [Bool])
validateStatesGHC pg comp_func modN entry chAll chAny b er@(ExecRes {final_state = s, conc_out = out}) = do
    (chck_res, chAllR, chAnyR) <- runCheck pg comp_func modN entry chAll chAny b er
    
    -- If check result is an HVal, coerce to an exception or a Bool. Additionally, track if the check result was a SrcErr.
    m_val_or_except <- case chck_res of 
            HVal v -> liftIO . timeout (5 * 10 * 1000) $ (unsafeCoerce v :: IO (Either SomeException Bool))
            SrcErr _ -> return Nothing

    let outStr = T.unpack $ printHaskell s out
   
    -- Translate to ValidateRes
    let val_res = case m_val_or_except of
            Nothing -> ValidationSrcError (case chck_res of SrcErr se -> se; _ -> error "validateStatesGHC: source error flagged but no available SourceError object")
            Just (Left e) | show e == "<<timeout>>" -> ValidationTimeout
                          | otherwise -> ValidationRTError
            Just (Right b_) -> if b_ && outStr /= "error" && outStr /= "undefined" then Valid else Invalid

    -- TODO[Jacob]: Currently using ValidationRTError to mean "a runtime error that was not the desired result of validation".
    -- If both symbolic execution and GHC validation found a runtime error, convert the ValidateRes to Valid.
    let val_res' = case val_res of 
            ValidationRTError -> if errorRaised s then Valid else ValidationRTError
            v -> v 

    chAllR' <- liftIO $ (mapM unsafeCoerce chAllR :: IO [Either SomeException Bool])
    let chAllR'' = rights chAllR'

    chAnyR' <- liftIO $ (mapM unsafeCoerce chAnyR :: IO [Either SomeException Bool])
    let chAnyR'' = rights chAnyR'

    let val_res'' = case (val_res', and chAllR'') of
                    (Valid, False) -> Invalid
                    (v_res, _) -> v_res

    return (val_res'', chAnyR'')

createDeclsStr :: PrettyGuide -> State t -> TypeEnv -> [String]
createDeclsStr pg s = map (creatDeclStr pg s) . H.toList

createDecls :: GhcMonad m => PrettyGuide -> State t -> TypeEnv -> m ()
createDecls pg s = mapM_ runDecls . createDeclsStr pg s

adjustDynFlags :: GhcMonad m => m ()
adjustDynFlags = do
    dyn <- getSessionDynFlags
    let dyn2 = F.foldl' xopt_set dyn [MagicHash, UnboxedTuples, DataKinds, BangPatterns]
        dyn3 = wopt_unset dyn2 Opt_WarnOverlappingPatterns
        dyn4 = dyn3 { generalFlags = ES.insert Opt_Hpc (generalFlags dyn3) }
    _ <- setSessionDynFlags dyn4
    return ()

data CheckRes = HVal HValue | SrcErr SourceError

runCheck :: GhcMonad m => PrettyGuide -> String -> HS.HashSet (Maybe T.Text) -> String -> [String] -> [String] -> Bindings -> ExecRes t -> m (CheckRes, [HValue], [HValue])
runCheck init_pg comp_func modN entry chAll chAny b er@(ExecRes {final_state = s, conc_args = ars, conc_out = out}) = do
    let v = case findFunc (tyvar_env s) (T.pack entry) (HS.toList modN) (expr_env s) of
                Left (x, _) -> x
                Right x -> error $ "runCheck: expected Left but got Right " ++ show x
    let e = mkApp $ Var v:ars
    let pg = updatePGValAndTypeNames e
           . updatePGValAndTypeNames out
           $ updatePGValAndTypeNames (varIds v) init_pg

    let (mvTxt, arsTxt, outTxt, _) = printInputOutput pg v b er 
        mvStr = T.unpack mvTxt
        arsStr = T.unpack arsTxt
        outStr = T.unpack outTxt

    let arsType = T.unpack $ mkTypeHaskellPG pg (typeOf (tyvar_env s) e)
        outType = case typeOf (tyvar_env s) out of
                            TyUnknown -> ""
                            t -> " :: " ++ (T.unpack $ mkTypeHaskellPG pg t)

    -- If we are returning a primitive type (Int#, Float#, etc.) wrap in a constructor so that `==` works
    let pr_con = case typeOf (tyvar_env s) out of
                        TyLitInt -> "I# "
                        TyLitDouble -> "D# "
                        TyLitFloat -> "F# "
                        TyLitChar -> "C# "
                        _ -> ""

    let comp_func' = case comp_func of
                        x:_ | 'a' <= x && x <= 'z' -> "`" ++ comp_func ++ "`"
                        _ -> comp_func

    let chck = case outStr == "error" || outStr == "undefined" || outStr == "?" of
                    False -> mvStr ++ "Control.Exception.try (evaluate (" ++ pr_con ++ "(" ++ arsStr ++ ") " ++ comp_func' ++ " " ++ pr_con ++ "("
                                        ++ outStr ++ outType ++ ")" ++ ")) :: IO (Either SomeException Bool)"
                    True -> mvStr ++ "Control.Exception.try (evaluate ( (" ++ pr_con ++ "(" ++ arsStr ++ " :: " ++ arsType ++ ")" ++
                                                    ") " ++ comp_func' ++ " " ++ pr_con ++ "(" ++ arsStr ++ "))) :: IO (Either SomeException Bool)"

    -- TODO[Jacob]: Currently determining source error here and runtime error later. Consider changing
    chck_res <- defaultErrorHandler defaultFatalMessager defaultFlushOut
            $ handleSourceError (\err -> return $ SrcErr err) 
                                (do hv <- compileExpr chck; return $ HVal hv)

    let chArgs = ars ++ [out] 
    let chAllStr = map (\f -> T.unpack $ printHaskellPG pg s $ mkApp ((simpVar $ T.pack f):chArgs)) chAll
    let chAllStr' = map (\str -> "Control.Exception.try (evaluate (" ++ str ++ ")) :: IO (Either SomeException Bool)") chAllStr

    chAllR <- mapM compileExpr chAllStr'

    let chAnyStr = map (\f -> T.unpack $ printHaskellPG pg s $ mkApp ((simpVar $ T.pack f):chArgs)) chAny
    let chAnyStr' = map (\str -> "Control.Exception.try (evaluate (" ++ str ++ ")) :: IO (Either SomeException Bool)") chAnyStr

    chAnyR <- mapM compileExpr chAnyStr'

    return (chck_res, chAllR, chAnyR)

loadToCheck :: GhcMonad m => [FilePath] -> [FilePath] -> HS.HashSet (Maybe T.Text) -> [GeneralFlag] -> m ()
loadToCheck proj src modN gflags = do
        _ <- loadProj Nothing proj src gflags simplTranslationConfig

        let mdN = map (mkModuleName . T.unpack) . catMaybes $ HS.toList modN
        let imD = map simpleImportDecl mdN

        setContext (map IIDecl imD ++ loadStandardSet)

loadStandard :: Ghc ()
loadStandard = setContext loadStandardSet

loadStandardSet :: [InteractiveImport]
loadStandardSet =
    let primN = mkModuleName "GHC.Prim"
        primImD = simpleImportDecl primN

        extsN = mkModuleName "GHC.Exts"
        extsImD = simpleImportDecl extsN

        prN = mkModuleName "Prelude"
        prImD = simpleImportDecl prN

        exN = mkModuleName "Control.Exception"
        exImD = simpleImportDecl exN

        coerceN = mkModuleName "Data.Coerce"
        coerceImD = simpleImportDecl coerceN

        charN = mkModuleName "Data.Char"
        charD = simpleImportDecl charN
    in
    [IIDecl primImD, IIDecl extsImD, IIDecl prImD, IIDecl exImD, IIDecl coerceImD, IIDecl charD]

simpVar :: T.Text -> Expr
simpVar s = Var (Id (Name s Nothing 0 Nothing) TyBottom)

runHPC :: FilePath -> String -> String -> String -> [ExecRes t] -> IO ()
runHPC src meas_with modN entry in_out = do
    let calls = map (\(ExecRes { final_state = s, conc_args = i, conc_out = o })-> toCall modN entry s i o) in_out

    runHPC' src meas_with modN calls

-- Compile with GHC, and check that the output we got is correct for the input
runHPC' :: FilePath -> String -> String -> [String] -> IO ()
runHPC' src meas_with modN ars = do
    srcCode <- readFile src
    let ext = dropWhile (/= '.') src
        dir = takeDirectory src
        -- srcCode' = removeModule modN srcCode

    let spces = "  "

    let meas_with' = if meas_with == "" then "" else " $ " ++ meas_with ++ " "
        chck = intercalate ("\n" ++ spces) $ map (\s -> "Ex.try (print " ++ meas_with' ++ "(" ++ s ++ ")) :: IO (Either Ex.SomeException ())") ars

    let mainFunc = "\n\nmain_internal_g2 :: IO ()\nmain_internal_g2 =do\n"
                            ++ spces ++ chck ++ "\n" ++ spces ++  "return ()\n" ++ spces


    createDirectoryIfMissing False "hpc"
    let origMod = modN
        origFile = "hpc/" ++ origMod
        mainMod = "Main_" ++ modN
        mainFile = "hpc/" ++ mainMod

    let handleExists e
          | isDoesNotExistError e = return ()
          | otherwise = throwIO e
    removeFile (mainMod ++ ".tix") `catch` handleExists

    writeFile (origFile ++ ext) srcCode
    writeFile (mainFile ++ ".hs") ("module CallForHPC where\n\nimport qualified Control.Exception as Ex\nimport Data.Char\nimport " ++ modN ++ "\n" ++ mainFunc)

    callProcess "ghc" $ ["-main-is", "CallForHPC.main_internal_g2", "-fhpc"
                        , mainFile ++ ".hs", src, "-o", mainFile, "-O0", "-i" ++ dir]
    callProcess ("./" ++ mainFile) []

    callProcess "hpc" ["report", mainMod, "--per-module", "--srcdir=hpc", "--hpcdir=../.hpc"]

toCall :: String -> String -> State t -> [Expr] -> Expr -> String
toCall modN entry s ars _ =
    let
        v = case findFunc (tyvar_env s) (T.pack entry) [Just $ T.pack modN] (expr_env s) of
                    Left (x, _) -> x
                    Right x -> error $ "toCall: expected Left but got Right " ++ show x
        e = mkApp (Var v:ars)
        t = typeOf (tyvar_env s) e
        pg = setStrictCase True $ mkPrettyGuide (exprNames e)

        str_e = printHaskellPG pg s $ e
        str_t = mkTypeHaskellPG pg t
    in
    T.unpack $ str_e <> " :: " <> str_t

loadSession :: GhcMonad m => [FilePath] -> [FilePath] -> HS.HashSet (Maybe T.Text) -> [GeneralFlag] -> m ()
loadSession proj src modN gflags = do
    adjustDynFlags
    loadToCheck (map dirPath src ++ proj) src modN gflags

-- | Load the passed module(s) into GHC, and check that the `ExecRes` results are correct.
validateState :: GhcMonad m => String -> HS.HashSet (Maybe T.Text) -> String -> [String] -> [String] -> Bindings
               -> ExecRes t
               -> m ValidateRes
validateState comp_func modN entry chAll chAny b in_out = do
        let s = final_state in_out
        let pg = updatePGValNames (concatMap (map Data . dataCon) $ type_env s)
                       . updatePGTypeNames (type_env s)
                       . flip (foldr updateQualMods) (catMaybes $ HS.toList modN)
                       . setStrictCase True
                       $ mkPrettyGuide ()
        _ <- createDecls pg s (H.filter (\x -> adt_source x == ADTG2Generated) (type_env s))
        rs_anys <- validateStatesGHC pg comp_func modN entry chAll chAny b in_out

        return (fst rs_anys)

printStateOutput :: (GhcMonad m) => Config -> Id -> Bindings
               -> Maybe ValidateRes
               -> ExecRes t
               -> m ()
printStateOutput config entry b mval_res exec_res@(ExecRes { final_state = s }) = do
    let pg = mkPrettyGuide (exprNames $ conc_args exec_res)
    let (mvp, inp, outp, handles_) = printInputOutput pg entry b exec_res
        sym_gen_out = fmap (printHaskellPG pg s) $ conc_sym_gens exec_res
        
    let print_method m i o = m <> i <> " = " <> o

    let state_output_text = print_method mvp inp outp

    let print_valid = isJust mval_res
    when (print_output config) (do
        when print_valid $ do
            let val_res = fromJust mval_res -- know mval_res is Just, can use fromJust

            (case val_res of
                ValidationSrcError vse -> printException vse
                _ -> return ())
            
            liftIO (case val_res of
                Valid -> putStr "✓ "
                Invalid -> putStr "✗ "
                ValidationTimeout -> putStr "✗TO "
                ValidationSrcError _ -> putStr "✗Src "
                ValidationRTError -> putStr "✗RT ")
        
        liftIO $ case sym_gen_out of
            S.Empty -> T.putStrLn state_output_text
            _ -> T.putStrLn $ state_output_text <> "\t| generated: " <> T.intercalate ", " (F.toList sym_gen_out)
        
        liftIO $ if handles_ /= "" then T.putStrLn handles_ else return ())

toEnclodeFloat :: ASTContainer m Expr => m -> m
toEnclodeFloat = modifyASTs go
    where
        go (App (Data (DataCon { dc_name = dcn })) (Lit (LitFloat f)))
            | not (isNaN f), not (isInfinite f), not (isNegativeZero f), nameOcc dcn == "F#" =
                let (m, n) = decodeFloat f in mkApp [encFloat, iCon $ Lit (LitInteger m), iCon $ Lit (LitInt $ toInteger n)]
        go (App (Data (DataCon { dc_name = dcn })) (Lit (LitDouble f)))
            | not (isNaN f), not (isInfinite f), not (isNegativeZero f), nameOcc dcn == "D#" =
                let (m, n) = decodeFloat f in mkApp [encFloat, iCon $ Lit (LitInteger m), iCon $ Lit (LitInt $ toInteger n)]
        go (Lit (LitFloat f))
            | not (isNaN f), not (isInfinite f), not (isNegativeZero f) =
                let (m, n) = decodeFloat f in mkApp [encFloat, iCon $ Lit (LitInteger m), iCon $ Lit (LitInt $ toInteger n)]
        go (Lit (LitDouble f))
            | not (isNaN f), not (isInfinite f), not (isNegativeZero f) =
                let (m, n) = decodeFloat f in mkApp [encFloat, iCon $ Lit (LitInteger m), iCon $ Lit (LitInt $ toInteger n)]
        go e = e

        iCon = App (Data (DataCon { dc_name = Name "Z#" Nothing 0 Nothing, dc_type = TyUnknown, dc_exist_tyvars = [], dc_univ_tyvars = [] }))
        encFloat = Var (Id (Name "encodeFloat" Nothing 0 Nothing) TyUnknown)
